### ISSUE TITLE
It would be awesome to have Caching of the JWT Token

### ISSUE THREAD

**Issue by code040** [EclecticIQ/cabby#31]
Currently if you specify a JWT url, and username/password, on each request the Token is fetched again. this has a big performance impact. It would be great if there would be a (persistent) caching option for the token, and automatic expiry detection, so that  a new token is fetched (UNAUTHENTICATED) 

https://github.com/Intelworks/cabby/blob/master/cabby/dispatcher.py#L69

**Comment by traut** [comment]
implemented in 0.1.13
