### ISSUE TITLE
Unable to Read Proxied Content with Taxii-Poll

### ISSUE THREAD

**Issue by nickwallen** [EclecticIQ/cabby#34]
### Goal

I am trying to use `taxii-proxy` to fetch some data from hailataxi.com and push into my own local collection.  
### Problem

Based on the size of the database file, it appears this is happening.  But when I try to use `taxii-poll` on my local collection it does not return any data.  Why is this?
1. The size of the data file indicates how much data roughly is in my collection.
   
   ```
   (opentaxii-venv)[root@source opentaxii]# ls -l data
   total 1804
   -rw-r--r--. 1 root root 1838080 Apr 20 20:50 data.db
   -rw-r--r--. 1 root root    3072 Apr 20 20:48 auth.db
   ```
2. Now proxy the data from hailataxii.com
   
   ```
   (opentaxii-venv)[root@source opentaxii]# taxii-proxy --poll-path http://hailataxii.com/taxii-data             
     --poll-collection guest.phishtank_com             
     --inbox-path http://localhost:9000/services/inbox             
     --inbox-collection hailataxii-phishtank             
     --binding urn:stix.mitre.org:xml:1.1             
     --inbox-username guest             
     --inbox-password guest             
     --begin 2016-04-20 
   2016-04-20 20:51:53,139 INFO: Sending Poll_Request to http://hailataxii.com/taxii-data
   2016-04-20 20:51:53,146 INFO: Starting new HTTP connection (1): hailataxii.com
   2016-04-20 20:51:53,624 INFO: Response received for Poll_Request from http://hailataxii.com/taxii-data
   2016-04-20 20:51:53,800 INFO: Sending Inbox_Message to http://localhost:9000/services/inbox
   ...
   ```
3. Check the size of the data file again.  Its bigger!  We must have successfully received data.
   
   ```
   (opentaxii-venv)[root@source opentaxii]# ls -l data
   total 2736
   -rw-r--r--. 1 root root 2791424 Apr 20 20:51 data.db
   -rw-r--r--. 1 root root    3072 Apr 20 20:48 auth.db
   ```
4. But there is no data.  Why is that?
   
   ```
   (opentaxii-venv)[root@source opentaxii]# taxii-poll --discovery http://localhost:9000/services/discovery -c hailataxii-phishtank
   2016-04-20 20:55:01,873 INFO: Polling using data binding: ALL
   2016-04-20 20:55:01,874 INFO: Sending Discovery_Request to http://localhost:9000/services/discovery
   2016-04-20 20:55:01,880 INFO: Starting new HTTP connection (1): localhost
   2016-04-20 20:55:01,886 INFO: Response received for Discovery_Request from http://localhost:9000/services/discovery
   2016-04-20 20:55:01,888 INFO: 3 services discovered
   2016-04-20 20:55:01,888 INFO: Sending Poll_Request to http://localhost:9000/services/poll
   2016-04-20 20:55:01,890 INFO: Starting new HTTP connection (1): localhost
   2016-04-20 20:55:01,898 INFO: Response received for Poll_Request from http://localhost:9000/services/poll
   2016-04-20 20:55:01,899 INFO: 0 blocks polled
   ```
### Configuration

services.yml

```

---
#
# discovery: used by a TAXII Client to discover available TAXII Service
#
- id: discovery
  type: discovery
  address: /services/discovery
  description: Discovery service
  advertised_services:
    - inbox
    - collection
    - poll
  protocol_bindings:
    - urn:taxii.mitre.org:protocol:http:1.0

#
# inbox: used by a TAXII Client to push information to a TAXII Server
#
- id: inbox
  type: inbox
  address: /services/inbox
  description: Inbox for hailataxii.com feed
  destination_collection_required: yes
  accept_all_content: no
  authentication_required: yes
  protocol_bindings:
    - urn:taxii.mitre.org:protocol:http:1.0

#
# collection_management: used by a TAXII Client to request information about
# available data collections or request a subscription.
#
- id: collection
  type: collection_management
  address: /services/collection
  description: Collection management service for hailataxii.com feed
  protocol_bindings:
    - urn:taxii.mitre.org:protocol:http:1.0

#
# poll: used by a TAXII Client to request information from a TAXII Server
#
- id: poll
  type: poll
  address: /services/poll
  description: Poll for hailataxii.com feed
  subscription_required: no
  authentication_required: no
  protocol_bindings:
    - urn:taxii.mitre.org:protocol:http:1.0
```

collections.yml

```

---
- name: hailataxii-phishtank
  available: true
  accept_all_content: true
  supported_content:
    - urn:stix.mitre.org:xml:1.0
    - urn:stix.mitre.org:xml:1.1
  service_ids:
    #- discovery
    - inbox
    - collection
    - poll
```

**Comment by traut** [comment]
@nickwallen looking at the configs, I noticed that your Inbox does not have any `supported_content` bindings specified and `accept_all_content` is set to `no`. That would mean that OpenTAXII ignores all incoming blocks (without throwing an error) because they do not match specified supported content bindings. Could you try again but with `supported_content` [specified](https://github.com/EclecticIQ/OpenTAXII/blob/master/examples/services.yml#L20)? 

DB may grow because OpenTAXII stores raw inbox messages [by default](https://github.com/EclecticIQ/OpenTAXII/blob/master/opentaxii/defaults.yml#L5).

**Comment by traut** [comment]
also, if my hunch is correct, there should be a warning in OpenTAXII log file

**Comment by nickwallen** [comment]
Yes, you are right.  I changed it to the following and it is now working.  I had a hard time finding the docs that described how to do this, but perhaps I just overlooked them.  I saw the examples, but the examples don't really describe what they are trying to achieve.  It took a lot of trial-and-error.

```
- id: inbox
  type: inbox
  address: /services/inbox
  destination_collection_required: yes
  accept_all_content: yes
  supported_content:
    - urn:stix.mitre.org:xml:1.1.1
  authentication_required: no
  protocol_bindings:
    - urn:taxii.mitre.org:protocol:http:1.0
```

**Comment by nickwallen** [comment]
Is `save_raw_inbox_message` documented anywhere?  I don't understand what that is supposed to do.

**Comment by code040** [comment]
You are correct, the documentation at https://opentaxii.readthedocs.org/en/stable/ does not mention this! we will have to adjust this to make sure all the options (also for services) are listed more thoroughly.

**Comment by traut** [comment]
yeah, it looks like a gap in the documentation. Configuration options are [not explained](https://opentaxii.readthedocs.org/en/latest/configuration.html#creating-services-and-collections), we just provide examples.
`save_raw_inbox_messages` is not in documentation too. If it is set to `yes` (true), OpenTAXII will store all inbox messages (accepted or ignored) for bookkeeping.

I'll add these items to my todo list.

**Comment by traut** [comment]
I'm closing this issue and noting that documentation should be extended
