### ISSUE TITLE
Contact email in README bounces

### ISSUE THREAD

**Issue by mikenerone** [EclecticIQ/cabby#39]
Sorry, wasn't sure how else to reach you. README provides the contact email `cabby@eclecticiq.com`. When sending to this address, the mail bounces with the message (apparently that address is aliased to Engineering@):
```
Your message to Engineering@eclecticiq.com couldn't be delivered.
The group Engineering only accepts messages from people in its organization or on its allowed senders list, and your email address isn't on the list.
```

**Comment by aukjan** [comment]
Hi @mikenerone, Thank you for your message. I will look into this, and fix it. If you want, you can send me the message right now using "aukjan  @  eclecticiq . com"
