### ISSUE TITLE
Proposal: make default taxii-push binding urn:stix.mitre.org:xml:1.2

### ISSUE THREAD

**Issue by chorsley** [eclecticiq/cabby#42]
I'd like feedback on making the default binding for taxii-push urn:stix.mitre.org:xml:1.2. My understanding is that 1.1.1 docs should pass 1.2 schema validation, so this may remove the need to specify any --binding arg when dealing with either 1.1.1 or 1.2 docs.

**Comment by erwin-eiq** [comment]
According to https://stixproject.github.io/releases/versioning/ you are correct, a minor version bump should be backwards compatible so we might as well default to 1.2.
