### ISSUE TITLE
Pushing multiple file in one command

### ISSUE THREAD

**Issue by zacharycheng** [EclecticIQ/cabby#52]
Is it possible to push more than one file content to the collection in a single command, like [ taxii-push --path http://ip.address:port/services/inbox --content-file * --dest collection ]? I tried this command and I got the following response: [taxii-push: error: unrecognized arguments] Thanks

**Comment by traut** [comment]
@zacharycheng no, this is not supported out of the box. you can easily script it with python, using cabby as a library or extend cabby's functionality with a pull request!
