### ISSUE TITLE
Dockerfile missing '/'

### ISSUE THREAD

**Issue by FireRoad33** [eclecticiq/cabby#64]
```
Step 5/10 : COPY ./requirements.txt ./requirements-dev.txt /cabby
When using COPY with more than one source file, the destination must be a directory and end with a /
```
Fixed with a modification to the Dockerfile:
Orig line 6: `COPY ./requirements.txt ./requirements-dev.txt /cabby`
New Line 6: `COPY ./requirements.txt ./requirements-dev.txt /cabby/`

**Comment by andreasEIQ** [comment]
Thanks for reporting! Likely it wasn't caught as we use recent Docker versions with buildkit enabled, where this is not needed any more. But there's no harm in adding such a trailing slash for other users.

Would you be willing to open a pull request with the change?
