### ISSUE TITLE
Polling Fails

### ISSUE THREAD

**Issue by lospinoj** [eclecticiq/cabby#73]
Hello,

Trying to pull a freebie feed from https://limo.anomali.com/api/v1/taxii/taxii-discovery-service/. The published username/password is guest/guest. We're able to discover but when we try to poll any given collection it fails.

Help would be most appreciated.

Thanks,

Jeff

C:\scripts.py\cabby\discover>python -VV
Python 3.6.6 (default, Jan 29 2019, 17:21:24) [MSC v.1900 64 bit (AMD64)]

C:\scripts.py\cabby\discover>pip search cabby
cabby (0.1.20)  - TAXII client library
  INSTALLED: 0.1.20 (latest)

[taxii_pull_1.py.txt](https://github.com/eclecticiq/cabby/files/4172662/taxii_pull_1.py.txt)

[script_output_and_error.txt](https://github.com/eclecticiq/cabby/files/4172654/script_output_and_error.txt)

**Comment by traut** [comment]
@lospinoj server returns 400 HTTP status error and `Request Failed`:

```bash
% taxii-poll --path https://limo.anomali.com/api/v1/taxii/poll/ -c Emerging_Threats___Compromised_F68 --username guest --password guest -v
2020-02-08 13:23:43,946 cabby.cli.poll INFO: Polling using data binding: ALL
2020-02-08 13:23:43,947 cabby.dispatcher INFO: Sending Poll_Request to https://limo.anomali.com/api/v1/taxii/poll/
2020-02-08 13:23:43,947 cabby.dispatcher DEBUG: Request:
<taxii_11:Poll_Request xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="94996c39-02fc-4b44-b18d-218c00895f43" collection_name="Emerging_Threats___Compromised_F68">
  <taxii_11:Poll_Parameters allow_asynch="false">
    <taxii_11:Response_Type>FULL</taxii_11:Response_Type>
  </taxii_11:Poll_Parameters>
</taxii_11:Poll_Request>

2020-02-08 13:23:43,954 urllib3.connectionpool DEBUG: Starting new HTTPS connection (1): limo.anomali.com:443
2020-02-08 13:23:44,862 urllib3.connectionpool DEBUG: https://limo.anomali.com:443 "POST /api/v1/taxii/poll/ HTTP/1.1" 400 None
2020-02-08 13:23:44,863 cabby.dispatcher DEBUG: Response:
<taxii_11:Status_Message xmlns:taxii="http://taxii.mitre.org/messages/taxii_xml_binding-1" xmlns:taxii_11="http://taxii.mitre.org/messages/taxii_xml_binding-1.1" xmlns:tdq="http://taxii.mitre.org/query/taxii_default_query-1" message_id="3296175166951614284" in_response_to="94996c39-02fc-4b44-b18d-218c00895f43" status_type="FAILURE">
  <taxii_11:Message>Request Failed</taxii_11:Message>
</taxii_11:Status_Message>
...
```
It doesn't seem like a Cabby's issue, but maybe Anomali can provide more details on why the requests are failing?

**Comment by arcsector** [comment]
@lospinoj does this work with libtaxii and not with cabby?

**Comment by lospinoj** [comment]
Thanks @traut and @arcsector. Turns out that all the thing needs is an actual begin and end date. My meager understanding is that leaving out the begin and end dates should just grab everything that's there, but this site does not behave that way.

content_blocks = client.poll(collection_name='Abuse_ch_Ransomware_IPs_F135',begin_date='2019-01-09T00:00:00-04:00', end_date='2020-02-10T00:00:00-04:00',subscription_id=None, inbox_service=None,
    content_bindings=None, uri=None)

**Comment by lospinoj** [comment]
https://forum.anomali.com/t/cabby-for-limo-discovery-collections-work-not-poll/1653
