### ISSUE TITLE
Client subscribe does not utilize inbox service

### ISSUE THREAD

**Issue by joseph-gagnon** [eclecticiq/cabby#75]
Let me preface this with the fact that I am very new to OpenTAXII and Cabby.

I was attempting to set up a "subscriber" client that would subscribe to a collection. I located the inbox service that I wanted and made the subscription call as follows:

`sub_status = client.subscribe(collection_name='my-collection', inbox_service=inbox, uri='<URI to collection management service>')`

I then printed the information in `sub_status` to verify the subscription details. I found that the `delivery_params` property was empty (`None`).

I ran the code in a debugger and went into the Cabby python code. In `cabby/client11.py` the `subscribe` function is properly populating the dictionary object that is passed to the `_execute_request` function, with the details from the inbox I passed. However, the response object does not appear to have any of this information. It's as though it had been dropped.

**Comment by arcsector** [comment]
Hi there,

Can you post any info about the server you're contacting to subscribe?
Are you using OpenTAXII? If so, opentaxii has yet to implement subscription functionality, and as such won't return a response to cabby. This sounds like a server-side issue.

**Comment by joseph-gagnon** [comment]
Ah ha. Yes, I was using OpenTAXII as the server. What would you suggest I use for a more robust TAXII server?

**Comment by arcsector** [comment]
@joseph-gagnon i cant suggest a better open-source implenentation for TAXII v1. For TAXII v2 you can choose from either freetaxii or the cti oasis server

**Comment by erwin-eiq** [comment]
I'm closing this issue, since the original question has been answered. If there is a need for subscription functionality in opentaxii, please open an issue in that project.
