### ISSUE TITLE
Pulling STIX 2.0 data from Anomali Limo

### ISSUE THREAD

**Issue by wizardous23** [eclecticiq/cabby#80]
Hello, I am trying to subscribe to a collection within Anomali Limo (https://www.anomali.com/resources/limo). However, when using the URL (https://limo.anomali.com/taxii) I seem to be getting errors in the request and am not sure how to go about getting the STIX 2.0 data. I don't believe I am making a proper request using the cabby client correctly. How would I go about doing so?

**Comment by erwin-eiq** [comment]
@wizardous23 according to the information on https://www.anomali.com/resources/limo the url https://limo.anomali.com/taxii is for taxii2 clients (see attached screenshot). Cabby currently only supports taxii 1.0 and 1.1, so you should use https://limo.anomali.com/api/v1/taxii/taxii-discovery-service/ instead.

![2021-09-03-201429_grim](https://user-images.githubusercontent.com/88374684/132049706-aea3a088-81f2-4f89-80c4-0ce1e7f12e93.png)
